ADVprogramming ass2/Pages/Baskets.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADVprogramming_ass2.Model;

namespace ADVprogramming_ass2.Pages
{
    public class BasketsModel : PageModel
    {
        private readonly AppDBContext _dbContext;

        public BasketsModel(AppDBContext db)
        {
            _dbContext = db;
        }

        public List<BasketProductViewModel> BasketItems { get; set; }

        public class BasketProductViewModel
        {
            public Guid BasketId { get; set; }
            public int Quantity { get; set; }
            public string ProductName { get; set; }
            public string Description { get; set; }
        }

        public async Task OnGetAsync()
        {
            string userId = HttpContext.Session.GetString("UserId");

                //Guid.Parse(ItemId.ToString())
            if (!string.IsNullOrEmpty(userId))
            {
                var UIDtoGuid = Guid.Parse(userId.ToString());
                BasketItems = await _dbContext.Baskets
                    .Where(b => b.User_Id == UIDtoGuid)
                    .Select(b => new BasketProductViewModel
                    {
                        BasketId = b.Basket_Id,
                        Quantity = b.Quantity,
                        ProductName = b.Item.Item_Name,
                        Description = b.Item.Item_description
                    })
                    .ToListAsync();
            }
        }

        public async Task<IActionResult> OnPostCheckoutAsync()
        {
            string userId = HttpContext.Session.GetString("UserId");
            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToPage("/Login");
            }
            var UserIdGuid = Guid.Parse(userId.ToString());
            var basketItems = await _dbContext.Baskets.Where(b => b.User_Id == UserIdGuid).ToListAsync();
            if (!basketItems.Any())
            {
                return Page();
            }

            var order = new Order { User_Id = UserIdGuid };
            _dbContext.Orders.Add(order);
            await _dbContext.SaveChangesAsync();

            foreach(var item in basketItems)
            {
                var orderItem = new Order_Item
                {
                    Order_Id = order.Order_Id,
                    Item_Id = item.Item_Id,
                    Quantity = item.Quantity
                };
                _dbContext.OrderItems.Add(orderItem);

                _dbContext.Baskets.Remove(item);
            }
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("/Shop_Page", new { orderId = order.Order_Id});
        }

    }
}

ADVprogramming ass2/Pages/Delete_Item.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ADVprogramming_ass2.Model;
using System.Threading.Tasks;
using System.Linq;
using System.Reflection.Metadata.Ecma335;

namespace ADVprogramming_ass2.Pages
{
    public class Delete_ItemModel : PageModel
    {
        private readonly AppDBContext _dbConnection;

        public ItemsOnSaleModel Items { get; set; }
        public UserModel Users { get; set; }

        public Delete_ItemModel(AppDBContext context)
        {
            _dbConnection = context;
        }

        public void OnGet(Guid id)
        {
            Items = _dbConnection.Item.FirstOrDefault(t => t.Item_Id == id);
            Users = _dbConnection.User_Name.FirstOrDefault(t => t.User_Id == id);
        }

        public async Task<IActionResult> OnPostAsync(Guid id)
        {
            var itemToDelete = _dbConnection.Item.FirstOrDefault(t => t.Item_Id == id);
            var userToDelete = _dbConnection.User_Name.FirstOrDefault(t => t.User_Id == id);


            if (userToDelete != null)
            {
                _dbConnection.User_Name.Remove(userToDelete);

                await _dbConnection.SaveChangesAsync();

                return RedirectToPage("User_Database");
            }

            if (itemToDelete != null)
            {
                _dbConnection.Item.Remove(itemToDelete);

                await _dbConnection.SaveChangesAsync();

                return RedirectToPage("Item_Database");
            }

            else
            {
                return NotFound();
            }
        }

    }
}

ADVprogramming ass2/Pages/Edit_Item.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ADVprogramming_ass2.Model;
using System.Linq;
using System.Threading.Tasks;
using System.Reflection.Metadata.Ecma335;

namespace ADVprogramming_ass2.Pages
{
    public class Edit_ItemModel : PageModel
    {
        //hjmyshghsshggh
        private readonly AppDBContext _dbConnection;

        //hjmyshghsshggh
        [BindProperty]
        public ItemsOnSaleModel Items { get; set; }

        //hjmyshghsshggh
        public Edit_ItemModel(AppDBContext context)
        {
            _dbConnection = context; //hjmyshghsshggh
        }

        //hjmyshghsshggh
        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            //hjmyshghsshggh
            Items = await _dbConnection.Item.FindAsync(id);

            //hjmyshghsshggh
            if (Items == null)
            {
                return NotFound();//hjmyshghsshggh
            }

            //hjmyshghsshggh
            return Page();

        }

        //hjmyshghsshggh
        public async Task<IActionResult> OnPostAsync()
        {
            //hjmyshghsshggh
            //if (!ModelState.IsValid)
            //{
            //    return RedirectToPage("Index");
            //    return Page(); //hjmyshghsshggh
            //}
            var itemToUpdate = await _dbConnection.Item.FindAsync(Items.Item_Id);

            //hjmyshghsshggh
            if (itemToUpdate == null)
            {
                return NotFound(); //hjmyshghsshggh
            }

            //hjmyshghsshggh
            itemToUpdate.Item_Name = Items.Item_Name;
            itemToUpdate.Item_description = Items.Item_description;
            itemToUpdate.Supplier = Items.Supplier;
            itemToUpdate.Item_Type = Items.Item_Type;
            itemToUpdate.Quantity = Items.Quantity;
            itemToUpdate.QuantSold = Items.QuantSold;
            itemToUpdate.Price_Pound = Items.Price_Pound;

            //hjmyshghsshggh
            await _dbConnection.SaveChangesAsync();

            //hjmyshghsshggh
            return RedirectToPage("Item_Database");

        }
    }
}

ADVprogramming ass2/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ADVprogramming_ass2.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ADVprogramming ass2/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ADVprogramming_ass2.Model;

namespace ADVprogramming_ass2.Pages
{
    public class IndexModel : PageModel
    {
        public string egg { get; set; }

        


        public void OnGet()
        {
            egg = "egg";
        }
    }
}

ADVprogramming ass2/Pages/Item_DB_Screen.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ADVprogramming_ass2.Model;

namespace ADVprogramming_ass2.Pages
{
    public class Item_DB_ScreenModel : PageModel
    {
        private readonly AppDBContext _dbConnection;

        public ItemsOnSaleModel NewItem { get; set; }

        public Item_DB_ScreenModel(AppDBContext context)
        {
            _dbConnection = context;
        }

        public void OnGet()
        {
            NewItem = new ItemsOnSaleModel();
        }
        public IActionResult OnPost(ItemsOnSaleModel NewItem)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbConnection.Item.Add(NewItem);
            _dbConnection.SaveChanges();

            return RedirectToPage("Index");
        }
    }
}

ADVprogramming ass2/Pages/Item_Database.cshtml.cs
using ADVprogramming_ass2.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADVprogramming_ass2.Pages
{
    public class Item_DatabaseModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public List<ItemsOnSaleModel> Items { get; set; }

        private readonly AppDBContext _dbConnection;

        public Item_DatabaseModel(ILogger<IndexModel> logger, AppDBContext _db)
        {
            _logger = logger;

            _dbConnection = _db;
        }

        public void OnGet()
        {
            Items = _dbConnection.Item.ToList();
        }
    }
}

ADVprogramming ass2/Pages/Item_Sale_page.cshtml.cs
using ADVprogramming_ass2.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Net.Http.Headers;
using Microsoft.EntityFrameworkCore;

namespace ADVprogramming_ass2.Pages
{
    public class Item_Sale_pageModel : PageModel
    {
        private readonly AppDBContext _dbConnection;


        public Item_Sale_pageModel(AppDBContext context)
        {
            _dbConnection = context;
        }

        public ItemsOnSaleModel AddItem { get; set; }

        [BindProperty]
        public ItemsOnSaleModel Product { get; set; }

        public List<ItemsOnSaleModel> Items { get; set; } = new List<ItemsOnSaleModel>();

        public async Task OnGetAsync()
        {
            Items = await _dbConnection.Item.ToListAsync();
        }

        public async Task<IActionResult> OnPostAddProductAsync()
        {
            //hjmyshghsshggh
            if (!ModelState.IsValid)
            {
                Items = await _dbConnection.Item.ToListAsync();
                return Page();//hjmyshghsshggh
            }

            _dbConnection.Add(AddItem);
            await _dbConnection.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAddToBasketAsync(Guid ItemId)
        {
            var userID = Guid.Parse(HttpContext.Session.GetString("UserId"));
            var emptcheck = userID.ToString();
            if (string.IsNullOrEmpty(emptcheck))//string.IsNullOrEmpty(userID))
            {
                return RedirectToPage("/Login");
            }

            var item2str = ItemId.ToString();
            var productToAdd = await _dbConnection.Item.FindAsync(ItemId);
            if (productToAdd == null)
            {
                return NotFound();
            }

            var basketItem = new Basket { Item_Id = productToAdd.Item_Id, User_Id = userID };
            _dbConnection.Baskets.Add(basketItem);
            await _dbConnection.SaveChangesAsync();
            return RedirectToPage();
        }

    }
}

ADVprogramming ass2/Pages/Login.cshtml.cs
using ADVprogramming_ass2.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace ADVprogramming_ass2.Pages
{
    public class LoginModel : PageModel
    {
        private readonly AppDBContext _context;

        public LoginModel(AppDBContext context)
        {
            _context = context;
        }
        [BindProperty]
        public LoginInput Input { get; set; }

        public class LoginInput
        {
            [Required]
            [Display(Name = "UserName")]
            public string Username { get; set; }

            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }
        }

        public string Message { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var user = await _context.User_Name.FirstOrDefaultAsync(u => u.User_Name == Input.Username && u.Password == Input.Password);

            if (user == null)
            {
                Message = "InValid login attempt.";
                return Page();
            }
            var UIDtoString = user.User_Id.ToString();
            HttpContext.Session.SetString("UserId", UIDtoString);
            Message = "Login Successful.";
            return RedirectToPage("/Index");

        }

        public void OnGet()
        {
        }
    }
}

ADVprogramming ass2/Pages/Login_Page.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADVprogramming_ass2.Pages
{
    public class Login_PageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ADVprogramming ass2/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADVprogramming_ass2.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ADVprogramming ass2/Pages/Shop_page.cshtml.cs
using ADVprogramming_ass2.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ADVprogramming_ass2.Pages
{
    public class Shop_pageModel : PageModel

    {
        public ItemsOnSaleModel AddItem { get; set; }

        private readonly AppDBContext _dbConnection;

        public Shop_pageModel(AppDBContext db)
        {
            _dbConnection = db;
            //
            //
            //
        }



        public List<ItemsOnSaleModel> Items { get; set; } = new List<ItemsOnSaleModel>();

        [BindProperty]
        public ItemsOnSaleModel Product { get; set; }

        public async Task OnGetAsync()
        {
            Items = await _dbConnection.Item.ToListAsync();
        }

        public async Task<IActionResult> OnPostAddProductAsync()
        {
            if (!ModelState.IsValid)
            {
                Items = await _dbConnection.Item.ToListAsync();
                return Page();
            }

            _dbConnection.Add(AddItem);
            await _dbConnection.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAddToBasketAsync(Guid Item_Id)
        {
            //var userID = Guid.Parse(HttpContext.Session.GetString("UserId"));
            //var emptcheck = userID.ToString();

            var userId = HttpContext.Session.GetString("UserId");

            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToPage("/Login");
            }
            //^^Good :)
            //VVBad :(


            var productToAdd = await _dbConnection.Item.FindAsync(Item_Id);
            if (productToAdd == null)
            {
                return NotFound();
            }
            //^^
            var IdConvert = Guid.Parse(userId.ToString());

            var basketItem = new Basket { Item_Id = productToAdd.Item_Id, User_Id = IdConvert };
            _dbConnection.Baskets.Add(basketItem);
            await _dbConnection.SaveChangesAsync();

            return RedirectToPage();
        }



    }
}

ADVprogramming ass2/Pages/Signup.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ADVprogramming_ass2.Model;

namespace ADVprogramming_ass2.Pages
{
    public class SignupModel : PageModel
    {
        private readonly AppDBContext _dbConnection;
        public UserModel NewUser { get; set; }

        public SignupModel(AppDBContext context)
        {
            _dbConnection = context;
        }

        public void OnGet()
        {
            NewUser = new UserModel();
        }
        public IActionResult OnPost(UserModel NewUser)

        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbConnection.User_Name.Add(NewUser);
            _dbConnection.SaveChanges();

            return RedirectToPage("Index");
        }
    }
}

ADVprogramming ass2/Pages/User_Database.cshtml.cs
using ADVprogramming_ass2.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADVprogramming_ass2.Pages
{
    public class User_DatabaseModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public List<UserModel> Users { get; set; }

        private readonly AppDBContext _dbConnection;

        public User_DatabaseModel(ILogger<IndexModel> logger, AppDBContext _db)
        {
            _logger = logger;

            _dbConnection = _db;
        }

        public void OnGet()
        {
            Users = _dbConnection.User_Name.ToList();
        }
    }
}

ADVprogramming ass2/Pages/Baskets.cshtml
@page
@model ADVprogramming_ass2.Pages.BasketsModel
@{
}
@if (Model.BasketItems != null && Model.BasketItems.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Description</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model.BasketItems){
                <tr>
                    <td>@item.ProductName</td>
                    <td>@item.Description</td>
                    <td>@item.Quantity</td>
                </tr>
            }
        </tbody>
    </table>
}
else{
    <p>Your basket is empty.</p>
}
<form method="post" asp-page-handler="Checkout">
    <button type="submit" class="btn btn-primary">Checkout</button>
</form>

ADVprogramming ass2/Pages/Delete_Item.cshtml
@page "{id:Guid}"
@model ADVprogramming_ass2.Pages.Delete_ItemModel
@{
}
<h2>Confirm Deletion</h2>
<p>Are your sure you want to remove PERMENANTLY remove this item from the database</p>
<p>This cannot be undone</p>

<form method="post">
    <input type="hidden" asp-for="Items.Item_Id"/>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a asp-page="Item_Database" class="btn btn-secondary">Cancel</a>
</form>

ADVprogramming ass2/Pages/Edit_Item.cshtml
@page "{id:Guid}"
@model ADVprogramming_ass2.Pages.Edit_ItemModel

<h1>Edit Items</h1>

<form method="post">
    <input type="hidden" asp-for="Items.Item_Id" />

    <div class="form-group">
        <label for="Items_Item_Name">Name</label>
        <input asp-for="Items.Item_Name" class="form-control" />
    </div>

    <div class="form-group">
        <label for="Items_Item_Description">Description</label>
        <input asp-for="Items.Item_description"  class="form-control" />
    </div>

    <div class="form-group">
        <label for="Items_Supplier">supplier</label>
        <input asp-for="Items.Supplier" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Items_Type">Item type</label>
        <input asp-for="Items.Item_Type" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Items_Quantity">Quantity</label>
        <input asp-for="Items.Quantity" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Items_QuantSold">Amount sold</label>
        <input asp-for="Items.QuantSold" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Items_Price_Pound">Price</label>
        <input asp-for="Items.Price_Pound" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

ADVprogramming ass2/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="~/css/site.css">
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <main>
        <div class="container text-center" id="content">
        <div class="row align-items-start">
        <div class="col">
            <div class="flex-container">
                        <p>

                            <div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-smooth-scroll="true" class="scrollspy-example-2" tabindex="0">
                                <h4 id="scrollspyHeading1">News article</h4>
                                <img src="~/Images/RefPhotos/Rat.jpg" class="d-block w-10" alt="cutie"/>
                                <h4 id="scrollspyHeading2">News article</h4>
                                <img src="~/Images/RefPhotos/Rat.jpg" class="d-block w" alt="kitie" />
                                <h4 id="scrollspyHeading3">news arcticle</h4>
                                <img src="~/Images/RefPhotos/Rat.jpg" class="d-block w-10" alt="kitie" />
                            </div>
                        </p>
            </div>
        </div>
        <div class="col">
            <div class="flex-container">
                <p>Hello and welcome to Green Gardens, your one stop shop for gardening tools, supplies and plants. This website will let you order gardening accessories to your house, communicate with other Green Gardens users by provideing and reciveing tips and view out news letter. In addition we offer a loyalty card to let you or a loved one get special limited time deals and other such privlages.</p>
            </div>
        </div>

        </div>
        </div>
    </main>
</div>

ADVprogramming ass2/Pages/Item_DB_Screen.cshtml
@page
@model ADVprogramming_ass2.Pages.Item_DB_ScreenModel
@{
    ViewData["Title"] = "Database page";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="~/css/site.css">
<div class="text-center">
</div>
<div class="container border p-5">
    <form method="post">
        
        <!--Item name-->
        <div class="form-group row">
            <div class="col-4">
                <label>Item Name:</label>
            </div>
            <div class="col-8">
                <input asp-for="NewItem.Item_Name" class="form-control" />
            </div>
        </div>

        <!--Item Type-->
        <div class="form-group row">
            <div class="col-4">
                <label>Item Type:</label>
            </div>
            <div class="col-8">
                <input asp-for="NewItem.Item_Type" class="form-control" />
            </div>
        </div>

        <!--Supplier-->
        <div class="form-group row">
            <div class="col-4">
                <label>Supplier:</label>
            </div>
            <div class="col-8">
                <input asp-for="NewItem.Supplier" class="form-control" />
            </div>
        </div>

        <!--Quantity-->
        <div class="form-group row">
            <div class="col-4">
                <label>Starting quantity:</label>
            </div>
            <div class="col-8">
                <input asp-for="NewItem.Quantity" class="form-control" />
            </div>
        </div>

        <!--Price-->
        <div class="form-group row">
            <div class="col-4">
                <label>Price (£):</label>
            </div>
            <div class="col-8">
                <input asp-for="NewItem.Price_Pound" class="form-control" />
            </div>
        </div>

        <!--Description-->
        <div class="form-group row">
            <div class="col-4">
                <label>Description:</label>
            </div>
            <div class="col-8">
                <input asp-for="NewItem.Item_description" class="form-control" />
            </div>
        </div>

        <!--Buton-->
        <div class="form-group row">
            <div class="col">
                <button type="submit" class="btn btn-block btn-secondary">Add Item</button>
            </div>
        </div>



    </form>
</div>

ADVprogramming ass2/Pages/Item_Database.cshtml
@page
@model ADVprogramming_ass2.Pages.Item_DatabaseModel
@{
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="~/css/site.css">
<div class="text-center">
<main>
<table class="table">
    <thread>
        <tr>
            <th>ID</th>
            <th>Item Name</th>
            <th>Item Type</th>
            <th>Supplier</th>
            <th>Quantity</th>
            <th>Quantity Sold</th>
            <th>Price (£)</th>
        </tr>
    </thread>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>

                <td>@item.Item_Id</td>
                <td>@item.Item_Name</td>
                <td>@item.Item_Type</td>
                <td>@item.Supplier</td>
                <td>@item.Quantity</td>
                <td>@item.QuantSold</td>
                <td>@item.Price_Pound</td>
                <td>
                <a asp-page="/Edit_Item" asp-route-id="@item.Item_Id" class="btn btn-primary">Edit</a>
                <a asp-page="/Delete_Item" asp-route-id="@item.Item_Id" class="btn btn-danger">Delete</a>

                </td>

            </tr>


        }
    </tbody>
</table>
</main>
</div>

ADVprogramming ass2/Pages/Item_Sale_page.cshtml
@page "{id:Guid}"
@model ADVprogramming_ass2.Pages.Item_Sale_pageModel
@{
}
<p><strong>Test of data transfer</strong></p>
<input type="hidden" asp-for="Product.Item_Name" />
<div class="form-group">

    <form method="post" asp-page-handler="AddToBasket" asp-route-productId="Product.Item_Id">
        <button type="submit" class="btn btn-primary">Add To Basket</button>
    </form>
</div>
<button type="submit" class="btn btn-primary">Buy Item</button>

ADVprogramming ass2/Pages/Login.cshtml
@page
@model ADVprogramming_ass2.Pages.LoginModel
@{
}
<form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Input.Username"></label>
        <input asp-for="Input.Username" class="form-control" />
        <span asp-validation-for="Input.Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Password"></label>
        <input asp-for="Input.Password" class="form-control" />
        <span asp-validation-for="Input.Password" class="text-danger"></span>
        <div class="form-group">
            <input type="submit" value="Login" class="btn btn-primary" />
        </div>
    </div>
</form>

@if (!string.IsNullOrEmpty(Model.Message))
{
    <div class="alert alert-warning">@Model.Message</div>
}

ADVprogramming ass2/Pages/Shop_page.cshtml
@page
@model ADVprogramming_ass2.Pages.Shop_pageModel
@{
}
@foreach (var Item in Model.Items)
{
    <div class="card">
        <div class="card-header">
            @Item.Item_Name
        </div>
        <div class="card-body">
            <p class="card-text">@Item.Item_description</p>
            <form method="post" asp-page-handler="AddToBasket" asp-route-Item_Id="@Item.Item_Id">
                <button type="submit" class="btn btn-primary">Add to Basket</button>
            </form>
        </div>
    </div>
}